version: '3.5'
services:
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        healthcheck:
          test: CMD curl -sS 0.0.0.0:27017 || exit 1
          interval: 5s
          timeout: 5s
          retries:  10
          start_period: 15s
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: test
            MONGO_INITDB_DATABASE: readme-users
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db

    mongodb-express:
        image: mongo-express
        restart: always
        container_name: mongo-express
        healthcheck:
          test: CMD curl -sS 0.0.0.0:8081 || exit 1
          interval: 5s
          timeout: 5s
          retries:  10
          start_period: 15s
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
            ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
